version: '3.4'

services:
#docker run -p 9411:9411 openzipkin:2.23.2
  zipkin-server:
    image: openzipkin/zipkin:2.23.2
    ports:
      - 9411:9411
    networks:
      - hadesfranklyn-network

  naming-server:
    image: hadesfranklyn/naming-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    networks:
      - hadesfranklyn-network

  api-gateway:
    image: hadesfranklyn/api-gateway:0.0.1-SNAPSHOT
    ports:
      - 8765:8765
    depends_on:
      - naming-server
    networks:
      - hadesfranklyn-network
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
networks:
  hadesfranklyn-network:
    driver: bridge