server:
  port: 8100
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
    username: root # In production environment need to change
    password: root # In production environment need to change
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # In production disable this because it wastes performance.
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: book_service
    user: root # In production environment need to change
    password: root # In production environment need to change