server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 10
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s
  retry:
    instances:
      foo-bar:
        max-attempts: 5
        wait-duration: 1s
        enable-exponential-backoff: true
 
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
    username: root # In production environment need to change
    password: root # In production environment need to change
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # In production disable this because it wastes performance.
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
  flyway:
    url: jdbc:mysql://localhost:3306/cambio_service?useTimezone=true&serverTimezone=UTC
    user: root # In production environment need to change
    password: root # In production environment need to change
  sleuth:
    sampler:
      probability: 1.0
springdoc:
  show-actuator: true
  api-docs:
    path: book-service/v3/api-docs
  swagger-ui:
    config-url: /book-service/v3/api-docs/swagger-config
    url: /book-service/v3/api-docs