name: Continuous Integration with Github

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
        - uses: actions/checkout@v2
        
        - name: Log in to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{secrets.DOCKER_USERNAME}}
            password: ${{secrets.DOCKER_PASSWORD}}
